<a href="https://colab.research.google.com/github/laxmanreddysaddi/ML_24AG5A6617/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to NumPy Framework



In [1]:
import numpy as np

**1D-Array**

In [2]:
array1 =np.array([1,3,4,5])
print(array1)

[1 3 4 5]


**2D-Array**

In [3]:
array2=np.array([[2,4 ,5,6],[3,7,8,9]])
print(array2)

[[2 4 5 6]
 [3 7 8 9]]


In [4]:
array3=np.array([[1,3,4,5],[3,6,7,8],[5,6,7,8]])
print(array3)

[[1 3 4 5]
 [3 6 7 8]
 [5 6 7 8]]


**3D-Array**

In [7]:
array4=np.array([[[1,2,3],
                  [2,3,4],
                   [4,5,6]],

                 [[5,6,7],
                  [6,7,8],
                  [7,8,9]]])
print(array4)

[[[1 2 3]
  [2 3 4]
  [4 5 6]]

 [[5 6 7]
  [6 7 8]
  [7 8 9]]]


**Datatype of Numpy Array**

In [8]:
print(array1.dtype)

int64


**Size of NumpyArray**

In [10]:
print(array2.size)
print(array3.size)

8
12


**Dimension of Numpy Array**

In [12]:
print(array4.ndim)

3


**Numpy array shape attribute**

In [13]:
print(array2.shape)
print(array4.shape)

(2, 4)
(2, 3, 3)


**Numpy array itemsize attribute**

In [14]:
array5=np.array([[2,3,4,5],[3,5,6,7]])
print(array5.itemsize)

8


**Numpy array data attribute**

In [15]:
array=np.array([[1,3,4,5],[3,5,6,7]])
array1=np.array([[2,4,5,6],[5,6,77,7],[7,8,9,9]])
print(array.data)
print(array1.data)

**Access Array Elements using index**

In [16]:
array=np.array([3,4,6,7,8,9])
print(array[2])
print(array[5])
print(array[0])

6
9
3


**Modify Array using index**

In [17]:
array=np.array([3,5,6,7])
array[2]=9
print(array)

[3 5 9 7]


**2D  Numpy Array indexing**

In [20]:
array=np.array([[2,4,5,7],[6,8,9,1]])
print("3rd element at 1st row:",array[1,3] )
print("2nd element at 0st row:",array[0,2] )

3rd element at 1st row: 1
2nd element at 0st row: 5


**Numpy Statistics**

In [21]:
array=np.array([2,5,6,7])
median=np.median(array)
print(median)

5.5


In [25]:
array=np.array([2,5,4,7])
mean=np.mean(array)
print(mean)

4.5


In [26]:
array=np.array([2,6,8,9])
min=np.min(array)
print(min)

2


In [27]:
array=np.array([2,5,6,7])
max=np.max(array)
print(max)

7


In [28]:
marks=np.array([28,57,65,73])
std=np.std(marks)
print(std)

16.990806337546196


In [29]:
marks=np.array([28,57,65,73])
percentile=np.percentile(marks,50)
print(percentile)

61.0
